// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admins.sql

package dbgen

import (
	"context"
)

const countAdmins = `-- name: CountAdmins :one
SELECT count(*) FROM admins
`

func (q *Queries) CountAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOwner = `-- name: CreateOwner :one
INSERT INTO admins (id, role, status)
VALUES ($1, 'owner', 'active')
RETURNING id, role, status, created_at, updated_at
`

func (q *Queries) CreateOwner(ctx context.Context, id string) (Admin, error) {
	row := q.db.QueryRow(ctx, createOwner, id)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveAdmin = `-- name: GetActiveAdmin :one
SELECT id, role, status, created_at, updated_at
FROM admins
WHERE id = $1 AND status = 'active'
`

func (q *Queries) GetActiveAdmin(ctx context.Context, id string) (Admin, error) {
	row := q.db.QueryRow(ctx, getActiveAdmin, id)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockOwnerBootstrap = `-- name: LockOwnerBootstrap :exec
SELECT pg_advisory_xact_lock(hashtext('ez-vpn-lego.bootstrap-owner'))
`

func (q *Queries) LockOwnerBootstrap(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockOwnerBootstrap)
	return err
}
