// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditEvent = `-- name: CreateAuditEvent :exec
INSERT INTO audit_events (
    id,
    actor_admin_id,
    action,
    resource_type,
    resource_id,
    outcome,
    metadata
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateAuditEventParams struct {
	ID           string      `json:"id"`
	ActorAdminID pgtype.UUID `json:"actor_admin_id"`
	Action       string      `json:"action"`
	ResourceType string      `json:"resource_type"`
	ResourceID   pgtype.UUID `json:"resource_id"`
	Outcome      string      `json:"outcome"`
	Metadata     []byte      `json:"metadata"`
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) error {
	_, err := q.db.Exec(ctx, createAuditEvent,
		arg.ID,
		arg.ActorAdminID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Outcome,
		arg.Metadata,
	)
	return err
}

const createOutboxEvent = `-- name: CreateOutboxEvent :exec
INSERT INTO outbox_events (
    id,
    topic,
    aggregate_type,
    aggregate_id,
    payload
)
VALUES ($1, $2, $3, $4, $5)
`

type CreateOutboxEventParams struct {
	ID            string `json:"id"`
	Topic         string `json:"topic"`
	AggregateType string `json:"aggregate_type"`
	AggregateID   string `json:"aggregate_id"`
	Payload       []byte `json:"payload"`
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) error {
	_, err := q.db.Exec(ctx, createOutboxEvent,
		arg.ID,
		arg.Topic,
		arg.AggregateType,
		arg.AggregateID,
		arg.Payload,
	)
	return err
}
