// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operations.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeOperation = `-- name: CompleteOperation :one
UPDATE operations
SET status = 'succeeded', result = $2, finished_at = now(), updated_at = now()
WHERE id = $1 AND status IN ('queued', 'running')
RETURNING id, kind, status, requested_by, idempotency_key, input, result,
    error_code, attempts, available_at, started_at, finished_at, created_at,
    updated_at
`

type CompleteOperationParams struct {
	ID     string `json:"id"`
	Result []byte `json:"result"`
}

func (q *Queries) CompleteOperation(ctx context.Context, arg CompleteOperationParams) (Operation, error) {
	row := q.db.QueryRow(ctx, completeOperation, arg.ID, arg.Result)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.RequestedBy,
		&i.IdempotencyKey,
		&i.Input,
		&i.Result,
		&i.ErrorCode,
		&i.Attempts,
		&i.AvailableAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOperation = `-- name: CreateOperation :one
INSERT INTO operations (
    id,
    kind,
    status,
    requested_by,
    idempotency_key,
    input
)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (requested_by, idempotency_key) DO NOTHING
RETURNING id, kind, status, requested_by, idempotency_key, input, result,
    error_code, attempts, available_at, started_at, finished_at, created_at,
    updated_at
`

type CreateOperationParams struct {
	ID             string      `json:"id"`
	Kind           string      `json:"kind"`
	Status         string      `json:"status"`
	RequestedBy    pgtype.UUID `json:"requested_by"`
	IdempotencyKey string      `json:"idempotency_key"`
	Input          []byte      `json:"input"`
}

func (q *Queries) CreateOperation(ctx context.Context, arg CreateOperationParams) (Operation, error) {
	row := q.db.QueryRow(ctx, createOperation,
		arg.ID,
		arg.Kind,
		arg.Status,
		arg.RequestedBy,
		arg.IdempotencyKey,
		arg.Input,
	)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.RequestedBy,
		&i.IdempotencyKey,
		&i.Input,
		&i.Result,
		&i.ErrorCode,
		&i.Attempts,
		&i.AvailableAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOperationByIdempotencyKey = `-- name: GetOperationByIdempotencyKey :one
SELECT id, kind, status, requested_by, idempotency_key, input, result,
    error_code, attempts, available_at, started_at, finished_at, created_at,
    updated_at
FROM operations
WHERE requested_by = $1 AND idempotency_key = $2
`

type GetOperationByIdempotencyKeyParams struct {
	RequestedBy    pgtype.UUID `json:"requested_by"`
	IdempotencyKey string      `json:"idempotency_key"`
}

func (q *Queries) GetOperationByIdempotencyKey(ctx context.Context, arg GetOperationByIdempotencyKeyParams) (Operation, error) {
	row := q.db.QueryRow(ctx, getOperationByIdempotencyKey, arg.RequestedBy, arg.IdempotencyKey)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.RequestedBy,
		&i.IdempotencyKey,
		&i.Input,
		&i.Result,
		&i.ErrorCode,
		&i.Attempts,
		&i.AvailableAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
