// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pairing.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeTelegramPairingToken = `-- name: ConsumeTelegramPairingToken :one
UPDATE admin_pairing_tokens
SET consumed_at = now()
WHERE token_hash = $1
  AND consumed_at IS NULL
  AND expires_at > now()
RETURNING admin_id
`

func (q *Queries) ConsumeTelegramPairingToken(ctx context.Context, tokenHash []byte) (string, error) {
	row := q.db.QueryRow(ctx, consumeTelegramPairingToken, tokenHash)
	var admin_id string
	err := row.Scan(&admin_id)
	return admin_id, err
}

const createTelegramIdentity = `-- name: CreateTelegramIdentity :exec
INSERT INTO admin_identities (id, admin_id, provider, subject)
VALUES ($1, $2, 'telegram', $3)
`

type CreateTelegramIdentityParams struct {
	ID      string `json:"id"`
	AdminID string `json:"admin_id"`
	Subject string `json:"subject"`
}

func (q *Queries) CreateTelegramIdentity(ctx context.Context, arg CreateTelegramIdentityParams) error {
	_, err := q.db.Exec(ctx, createTelegramIdentity, arg.ID, arg.AdminID, arg.Subject)
	return err
}

const createTelegramPairingToken = `-- name: CreateTelegramPairingToken :execrows
INSERT INTO admin_pairing_tokens (token_hash, admin_id, expires_at)
SELECT $1, id, $2 FROM admins
WHERE id = $3 AND status = 'active'
`

type CreateTelegramPairingTokenParams struct {
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	AdminID   string             `json:"admin_id"`
}

func (q *Queries) CreateTelegramPairingToken(ctx context.Context, arg CreateTelegramPairingTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, createTelegramPairingToken, arg.TokenHash, arg.ExpiresAt, arg.AdminID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resolveTelegramIdentity = `-- name: ResolveTelegramIdentity :one
SELECT a.id, a.role, a.status, a.created_at, a.updated_at
FROM admins a
JOIN admin_identities i ON i.admin_id = a.id
WHERE i.provider = 'telegram' AND i.subject = $1 AND a.status = 'active'
`

func (q *Queries) ResolveTelegramIdentity(ctx context.Context, subject string) (Admin, error) {
	row := q.db.QueryRow(ctx, resolveTelegramIdentity, subject)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
