// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"
)

type Querier interface {
	CompleteOperation(ctx context.Context, arg CompleteOperationParams) (Operation, error)
	CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) error
	CreateOperation(ctx context.Context, arg CreateOperationParams) (Operation, error)
	CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetOperationByIdempotencyKey(ctx context.Context, arg GetOperationByIdempotencyKeyParams) (Operation, error)
	GetUser(ctx context.Context, id string) (User, error)
	ListUsers(ctx context.Context) ([]User, error)
}

var _ Querier = (*Queries)(nil)
