// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vpn.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateCredential = `-- name: ActivateCredential :exec
UPDATE credentials SET status = 'active', updated_at = now() WHERE id = $1
`

func (q *Queries) ActivateCredential(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, activateCredential, id)
	return err
}

const activateDevice = `-- name: ActivateDevice :exec
UPDATE devices SET status = 'active', updated_at = now() WHERE id = $1
`

func (q *Queries) ActivateDevice(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, activateDevice, id)
	return err
}

const activateNode = `-- name: ActivateNode :exec
UPDATE nodes SET status = 'active', updated_at = now() WHERE id = $1
`

func (q *Queries) ActivateNode(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, activateNode, id)
	return err
}

const activateProtocolInstances = `-- name: ActivateProtocolInstances :exec
UPDATE protocol_instances SET status = 'active', updated_at = now() WHERE node_id = $1
`

func (q *Queries) ActivateProtocolInstances(ctx context.Context, nodeID string) error {
	_, err := q.db.Exec(ctx, activateProtocolInstances, nodeID)
	return err
}

const countNodes = `-- name: CountNodes :one
SELECT count(*) FROM nodes
`

func (q *Queries) CountNodes(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countNodes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createConfigRevision = `-- name: CreateConfigRevision :exec
INSERT INTO config_revisions (id, node_id, state, content_hash, content)
VALUES ($1, $2, 'candidate', $3, $4)
`

type CreateConfigRevisionParams struct {
	ID          string `json:"id"`
	NodeID      string `json:"node_id"`
	ContentHash string `json:"content_hash"`
	Content     []byte `json:"content"`
}

func (q *Queries) CreateConfigRevision(ctx context.Context, arg CreateConfigRevisionParams) error {
	_, err := q.db.Exec(ctx, createConfigRevision,
		arg.ID,
		arg.NodeID,
		arg.ContentHash,
		arg.Content,
	)
	return err
}

const createCredential = `-- name: CreateCredential :exec
INSERT INTO credentials (id, device_id, node_id, driver, schema_version, status, secret)
VALUES ($1, $2, $3, $4, $5, 'disabled', $6)
`

type CreateCredentialParams struct {
	ID            string `json:"id"`
	DeviceID      string `json:"device_id"`
	NodeID        string `json:"node_id"`
	Driver        string `json:"driver"`
	SchemaVersion int32  `json:"schema_version"`
	Secret        []byte `json:"secret"`
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) error {
	_, err := q.db.Exec(ctx, createCredential,
		arg.ID,
		arg.DeviceID,
		arg.NodeID,
		arg.Driver,
		arg.SchemaVersion,
		arg.Secret,
	)
	return err
}

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (id, user_id, name, status)
VALUES ($1, $2, $3, 'disabled')
RETURNING id, user_id, name, status, expires_at, created_at, updated_at, deleted_at
`

type CreateDeviceParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
	Name   string `json:"name"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice, arg.ID, arg.UserID, arg.Name)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createNode = `-- name: CreateNode :one
INSERT INTO nodes (id, name, status, public_address)
VALUES ($1, $2, 'disabled', $3)
RETURNING id, name, status, created_at, updated_at, public_address
`

type CreateNodeParams struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	PublicAddress string `json:"public_address"`
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, createNode, arg.ID, arg.Name, arg.PublicAddress)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicAddress,
	)
	return i, err
}

const createProtocolInstance = `-- name: CreateProtocolInstance :exec
INSERT INTO protocol_instances (id, node_id, driver, schema_version, status, settings)
VALUES ($1, $2, $3, $4, 'disabled', $5)
`

type CreateProtocolInstanceParams struct {
	ID            string `json:"id"`
	NodeID        string `json:"node_id"`
	Driver        string `json:"driver"`
	SchemaVersion int32  `json:"schema_version"`
	Settings      []byte `json:"settings"`
}

func (q *Queries) CreateProtocolInstance(ctx context.Context, arg CreateProtocolInstanceParams) error {
	_, err := q.db.Exec(ctx, createProtocolInstance,
		arg.ID,
		arg.NodeID,
		arg.Driver,
		arg.SchemaVersion,
		arg.Settings,
	)
	return err
}

const failConfigRevision = `-- name: FailConfigRevision :exec
UPDATE config_revisions SET state = 'failed' WHERE id = $1 AND state = 'candidate'
`

func (q *Queries) FailConfigRevision(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, failConfigRevision, id)
	return err
}

const failOperation = `-- name: FailOperation :exec
UPDATE operations
SET status = 'failed', error_code = $2, finished_at = now(), updated_at = now()
WHERE id = $1 AND status IN ('queued', 'running', 'rolling_back')
`

type FailOperationParams struct {
	ID        string      `json:"id"`
	ErrorCode pgtype.Text `json:"error_code"`
}

func (q *Queries) FailOperation(ctx context.Context, arg FailOperationParams) error {
	_, err := q.db.Exec(ctx, failOperation, arg.ID, arg.ErrorCode)
	return err
}

const getActiveRealityInstance = `-- name: GetActiveRealityInstance :one
SELECT pi.id, pi.node_id, pi.settings, n.public_address
FROM protocol_instances pi
JOIN nodes n ON n.id = pi.node_id
WHERE pi.driver = 'xray-reality-vision'
  AND pi.status = 'active'
  AND n.status = 'active'
`

type GetActiveRealityInstanceRow struct {
	ID            string `json:"id"`
	NodeID        string `json:"node_id"`
	Settings      []byte `json:"settings"`
	PublicAddress string `json:"public_address"`
}

func (q *Queries) GetActiveRealityInstance(ctx context.Context) (GetActiveRealityInstanceRow, error) {
	row := q.db.QueryRow(ctx, getActiveRealityInstance)
	var i GetActiveRealityInstanceRow
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Settings,
		&i.PublicAddress,
	)
	return i, err
}

const listActiveRealityCredentials = `-- name: ListActiveRealityCredentials :many
SELECT c.id, c.secret, d.name
FROM credentials c
JOIN devices d ON d.id = c.device_id
JOIN users u ON u.id = d.user_id
WHERE c.node_id = $1
  AND c.driver = 'xray-reality-vision'
  AND c.status = 'active'
  AND d.status = 'active'
  AND u.status = 'active'
  AND d.deleted_at IS NULL
  AND u.deleted_at IS NULL
ORDER BY c.id
`

type ListActiveRealityCredentialsRow struct {
	ID     string `json:"id"`
	Secret []byte `json:"secret"`
	Name   string `json:"name"`
}

func (q *Queries) ListActiveRealityCredentials(ctx context.Context, nodeID string) ([]ListActiveRealityCredentialsRow, error) {
	rows, err := q.db.Query(ctx, listActiveRealityCredentials, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveRealityCredentialsRow{}
	for rows.Next() {
		var i ListActiveRealityCredentialsRow
		if err := rows.Scan(&i.ID, &i.Secret, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockVPNBootstrap = `-- name: LockVPNBootstrap :exec
SELECT pg_advisory_xact_lock(hashtext('ez-vpn-lego.bootstrap-vpn'))
`

func (q *Queries) LockVPNBootstrap(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockVPNBootstrap)
	return err
}

const lockXrayReconcile = `-- name: LockXrayReconcile :exec
SELECT pg_advisory_xact_lock(hashtext('ez-vpn-lego.xray-reconcile'))
`

func (q *Queries) LockXrayReconcile(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockXrayReconcile)
	return err
}

const supersedeVerifiedRevisions = `-- name: SupersedeVerifiedRevisions :exec
UPDATE config_revisions
SET state = 'superseded'
WHERE node_id = $1 AND state = 'verified'
`

func (q *Queries) SupersedeVerifiedRevisions(ctx context.Context, nodeID string) error {
	_, err := q.db.Exec(ctx, supersedeVerifiedRevisions, nodeID)
	return err
}

const verifyConfigRevision = `-- name: VerifyConfigRevision :exec
UPDATE config_revisions
SET state = 'verified', verified_at = now()
WHERE id = $1 AND state = 'candidate'
`

func (q *Queries) VerifyConfigRevision(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, verifyConfigRevision, id)
	return err
}
