d /run/ez-vpn-lego 0750 ezvpn ezvpn -
d /var/lib/ez-vpn-lego 0750 ezvpn ezvpn -
d /var/lib/ez-vpn-lego/candidates 0700 ezvpn ezvpn -
d /var/lib/ez-vpn-lego/backups 0700 root root -
d /etc/ez-vpn-lego 0750 root ezvpn -
d /etc/ez-vpn-lego/secrets 0750 root ezvpn -
d /etc/xray 2750 root xray -
